/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordenamientobusqueda;

import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Samu-Pc
 */
public class Principal extends javax.swing.JFrame {

    private final List<Integer> arregloDatos = new ArrayList<>();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblArrInit = new javax.swing.JLabel();
        txtNewItem = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelUltimo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblOrdenamiento = new javax.swing.JLabel();
        cbMetodo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        jLabel2.setText("Ordenamiento Arreglos Númericos");

        jPanel1.setPreferredSize(new java.awt.Dimension(550, 100));

        lblArrInit.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblArrInit.setText("-Vacío-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblArrInit)
                .addContainerGap(516, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblArrInit)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        lblArrInit.getAccessibleContext().setAccessibleName("-Vacío-");

        jScrollPane1.setViewportView(jPanel1);

        txtNewItem.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        btnAdd.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setMaximumSize(new java.awt.Dimension(45, 40));
        btnAdd.setMinimumSize(new java.awt.Dimension(45, 40));
        btnAdd.setPreferredSize(new java.awt.Dimension(45, 40));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelUltimo.setBackground(new java.awt.Color(255, 255, 153));
        btnDelUltimo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDelUltimo.setText("<- Último");
        btnDelUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelUltimoActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 153, 0));
        btnLimpiar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar!");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblOrdenamiento.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblOrdenamiento.setText("Pasos Ordenamiento:");

        cbMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Mejorado", "Optimizado", "Flag" }));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Valor Item:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Método Ordenar:");

        lblResultado.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblResultado.setText("-Vacio-");
        lblResultado.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResultado)
                .addContainerGap(597, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResultado)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        btnOrdenar.setBackground(new java.awt.Color(204, 255, 153));
        btnOrdenar.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 2, 10)); // NOI18N
        jLabel4.setText("Samuel Colmenares");

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 10)); // NOI18N
        jLabel5.setText("Programación Avanzada 1 - Uniremington");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrdenamiento)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbMetodo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDelUltimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar))
                            .addComponent(btnOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelUltimo)
                    .addComponent(btnLimpiar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnOrdenar))
                .addGap(31, 31, 31)
                .addComponent(lblOrdenamiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String itemText = txtNewItem.getText();

        if (itemText.isBlank() || itemText.trim().equals("")) {
            return;
        }

        try {
            this.arregloDatos.add(Integer.parseInt(itemText));

            if (this.arregloDatos.size() == 1) {
                Font font = new Font("Verdana", Font.PLAIN, 14);
                lblArrInit.setFont(font);
            }

            lblArrInit.setText(MetodosBurbuja.arregloToString(this.arregloDatos));
            txtNewItem.setText("");
            lblResultado.setText("Elementos nuevos.. Ordenar de nuevo.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor debe ser tipo numérico!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelUltimoActionPerformed
        if (this.arregloDatos.size() < 1) {
            return;
        }

        this.arregloDatos.remove(this.arregloDatos.size() - 1);
        lblArrInit.setText(MetodosBurbuja.arregloToString(this.arregloDatos));
        lblResultado.setText("Elementos diferentes.. Ordenar de nuevo.");
        if (this.arregloDatos.isEmpty()) {
            pintaArrVacio();
        }
    }//GEN-LAST:event_btnDelUltimoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Está seguro de borrar todo el arreglo?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.arregloDatos.clear();
            pintaArrVacio();
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        if (this.arregloDatos.size() < 3) {
            JOptionPane.showMessageDialog(null, "Es necesario más de 2 items para ordenar!");
            return;
        }

        String tipoMetodo = this.cbMetodo.getSelectedItem().toString();
        MetodosBurbuja metodos = new MetodosBurbuja();

        Integer arreglo[] = new Integer[this.arregloDatos.size()];
        arreglo = this.arregloDatos.toArray(arreglo);
        switch (tipoMetodo) {
            case "Mejorado":
                lblResultado.setText("<html><body>" + metodos.burbujaMejorada(arreglo) + "</body></html>");
                break;

            case "Optimizado":
                lblResultado.setText("<html><body>" + metodos.burbujaOptimizada(arreglo) + "</body></html>");
                break;

            case "Flag":
                lblResultado.setText("<html><body>" + metodos.burbujaFlag(arreglo) + "</body></html>");
                break;

            default:
                lblResultado.setText("<html><body>" + metodos.burbujaSimple(arreglo) + "</body></html>");
                break;
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    /**
     * Pinta los textos de un array vacío. 
     */
    private void pintaArrVacio() {
        lblArrInit.setText("-Vacio-");
        Font font = new Font("Verdana", Font.ITALIC, 14);
        lblArrInit.setFont(font);
        lblResultado.setText("-Vacio-");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelUltimo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JComboBox<String> cbMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArrInit;
    private javax.swing.JLabel lblOrdenamiento;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtNewItem;
    // End of variables declaration//GEN-END:variables
}
